// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IMapSystem } from "./IMapSystem.sol";
import { IMixingSystem } from "./IMixingSystem.sol";
import { IXOSystem } from "./IXOSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IMapSystem, IMixingSystem, IXOSystem {

}
