// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Encounter1, Encounter1Data, Encounter1TableId } from "./tables/Encounter1.sol";
import { EncounterTrigger1, EncounterTrigger1TableId } from "./tables/EncounterTrigger1.sol";
import { Encounterable1, Encounterable1TableId } from "./tables/Encounterable1.sol";
import { MapConfig1, MapConfig1TableId } from "./tables/MapConfig1.sol";
import { MonsterCatchAttempt1, MonsterCatchAttempt1TableId } from "./tables/MonsterCatchAttempt1.sol";
import { Monster1, Monster1TableId } from "./tables/Monster1.sol";
import { Movable1, Movable1TableId } from "./tables/Movable1.sol";
import { Obstruction1, Obstruction1TableId } from "./tables/Obstruction1.sol";
import { OwnedBy1, OwnedBy1TableId } from "./tables/OwnedBy1.sol";
import { Player1, Player1TableId } from "./tables/Player1.sol";
import { Position1, Position1TableId } from "./tables/Position1.sol";
import { MapConfig2, MapConfig2TableId } from "./tables/MapConfig2.sol";
import { Marker2, Marker2TableId } from "./tables/Marker2.sol";
import { Obstruction2, Obstruction2TableId } from "./tables/Obstruction2.sol";
import { OwnedBy2, OwnedBy2TableId } from "./tables/OwnedBy2.sol";
import { Player2, Player2TableId } from "./tables/Player2.sol";
import { Winner2, Winner2TableId } from "./tables/Winner2.sol";
import { Position2, Position2TableId } from "./tables/Position2.sol";
import { Map3, Map3TableId } from "./tables/Map3.sol";
import { Winner3, Winner3TableId } from "./tables/Winner3.sol";
