// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MonsterCatchResult1 {
  Missed,
  Caught,
  Fled
}

enum MonsterType1 {
  None,
  Eagle,
  Rat,
  Caterpillar
}

enum TerrainType1 {
  None,
  TallGrass,
  Boulder
}

enum MarkerType2 {
  None,
  X,
  O
}

enum TerrainType2 {
  None
}
