// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Marker, MarkerTableId } from "./tables/Marker.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Winner, WinnerTableId } from "./tables/Winner.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
